### ISSUE TITLE
Sending fractional amount in native transaction.

### ISSUE THREAD

**Issue by patrickdeshpande** [zulucrypto/stellar-api#1]
Hey, 

I am having problems sending transactions with fractional amounts of XLM. When passing "y.x" as amount in newNativePayment(), it is always rounded down to "y", which I suppose is expected because it is represented by BigInteger. I tried passing "y.x000000" like the AssetAmount class expects, but it still rounds down to y. Was wondering if I was doing something wrong, or if fractions aren't supported yet. Thanks.

**Comment by zulucrypto** [comment]
Hello,
Really sorry it took me so long to reply to this, I just now saw it! I fixed a lot of issues related to fractional amounts and `AssetAmount` in 0.2.0, could you please give this a try again?

**Comment by patrickdeshpande** [comment]
Hey, sure thing, I got around it for a bit by running a small nodejs service, but this will be great!

**Comment by zulucrypto** [comment]
@patrickdeshpande - I haven't seen any similar issues, so I'm closing this one. Please open another if you hit any problems!
