### ISSUE TITLE
Escrow Account

### ISSUE THREAD

**Issue by mohit67890** [zulucrypto/stellar-api#12]
Hi, Can you please guide me on how can I prepare an escrow account from this PHP SDK.

Basically, I wanted to submit a transaction wherein buyer of a good purchase a commodity and put XLM in an escrow account and when he receives the commodity, the buyer confirms the transaction and XLM are sent to the seller's address.

**Comment by zulucrypto** [comment]
Hi @mohit67890 - I've started a repository for example smart contracts and will try to work up an example of this there. 

This issue might be what you're looking for: https://github.com/zulucrypto/stellar-smart-contracts/issues/4

If not, please log a new issue in that repository.
