### ISSUE TITLE
Need a method TransactionBuilder::loadFromXdr($bytes) or equivalent

### ISSUE THREAD

**Issue by cballou** [zulucrypto/stellar-api#2]
First off, great work thus far. It was long overdue for PHP to have a Stellar SDK.

Handling multi-sig generally requires transactions to be signed piecemeal (by multiple parties at different times). Because of this, I believe it would be necessary for `TransactionBuilder` to support decoding an existing transaction XDR and return a new instance of `TransactionBuilder`. This would subsequently require that each of the accompanying XdrModel's have a decode method, i.e. `fromXdr($xdr)`, as well as an addition of `fromXdr()` to `XdrEncodableInterface`.

Here's a series of links (in call order) of how this is accomplished in the Python library:

* https://github.com/StellarCN/py-stellar-base/blob/master/stellar_base/builder.py#L290
* https://github.com/StellarCN/py-stellar-base/blob/master/stellar_base/transaction_envelope.py#L67
* https://github.com/StellarCN/py-stellar-base/blob/master/stellar_base/stellarxdr/StellarXDR_pack.py#L1859

Under the hood, this utilizes python's xdrlib.unpacker:

* https://github.com/python/cpython/blob/master/Lib/xdrlib.py#L132

**Comment by cballou** [comment]
Here's some preliminary work on a new `XdrDecoder` class for some of the easier methods:

```php
<?php

namespace ZuluCrypto\StellarSdk\Xdr;

use phpseclib\Math\BigInteger;
use ZuluCrypto\StellarSdk\Xdr\Iface\XdrEncodableInterface;

class XdrDecoder
{

    public static function signedInteger($value)
    {
        // pack() does not support a signed 32-byte int, so work around this with
        // custom encoding
        return (self::nativeIsBigEndian()) ? unpack('l', $value) : unpack('l', strrev($value));
    }

    public static function unsignedInteger($value)
    {
        // unsigned 32-bit big-endian
        return unpack('N', $value)[1];
    }

    public static function signedInteger64($value)
    {
        // pack() does not support a signed 64-byte int, so work around this with
        // custom encoding
        return (self::nativeIsBigEndian()) ? unpack('q', $value)[1] : pack('q', strrev($value))[1];
    }

    public static function unsignedInteger64($value)
    {
        // unsigned 64-bit big-endian
        return unpack('J', $value)[1];
    }

    public static function signedHyper($value)
    {
        return self::signedInteger64($value);
    }

    public static function unsignedHyper($value)
    {
        return self::unsignedInteger64($value);
    }

    public static function boolean($value)
    {
        return self::unsignedInteger($value);
    }

}
```

**Comment by zulucrypto** [comment]
I've started work on XDR decoding.

**Comment by cballou** [comment]
Any updates on the XDR decoding progress? If you post up a feature branch I may be able to start chipping away at pieces.

**Comment by zulucrypto** [comment]
@cballou - I'm currently working on decoding the `result_xdr` field into a `TransactionResult` but I do have the groundwork for decoding the rest of the XDR objects. 

I'm making good progress and hoping to finish that "soon", but I'd love some help on parsing XDR into a `TransactionBuilder` if you've got time! I'll push up my branch in the next few days and let you know when it's available.

**Comment by cballou** [comment]
Sure, let me know when it's up.

**Comment by zulucrypto** [comment]
@cballou - I've tagged 0.6.0 with support for converting XDR to PHP objects. Please open additional issues if you find a use case that's not supported or run into any problems!
