### ISSUE TITLE
Add support for bump sequence

### ISSUE THREAD

**Issue by tholder** [zulucrypto/stellar-api#24]
Being introduced in stellar core 10.0.0. Details https://www.reddit.com/r/Stellar/comments/970dye/please_read_migration_schedule_for_stellar_core/

Details regarding bump sequence:

https://www.stellar.org/developers/guides/concepts/list-of-operations.html#bump-sequence

The offical JS lib implementation:

https://stellar.github.io/js-stellar-sdk/node_modules_stellar-base_src_operations_bump_sequence.js.html

**Comment by zulucrypto** [comment]
Thanks for logging this. Bump sequence support is mostly done, it should be finished in early September.

**Comment by zulucrypto** [comment]
Full BumpSequence support is now available in 0.7.0. Please open another issue if you encounter any problems!
