### ISSUE TITLE
[Question] What is the best method to monitor an account for payments ?

### ISSUE THREAD

**Issue by gituser** [zulucrypto/stellar-api#26]
Hi.

We're in the process of integrating Stellar into our exchange service and wanted to ask what is the best method to monitor payments to our account via your API library.

We're using your example to get all payments to our account:

```
use ZuluCrypto\StellarSdk\Server;
$server = Server::testNet();
$account = $server->getAccount('XXXXX');
$currentCursor = null;
while (true) {
    $resultsPerPage = 10;
    $payments = $account->getPayments(null, $resultsPerPage);
    $seenResults = 0;
    foreach ($payments as $payment) {
        // If the same cursor shows up twice, we're repeating results and should exit
if (method_exists($payment,'getTransactionHash')) $txid= $payment->getTransactionHash(); else $txid = 'n/a';
        if ($payment->getPagingToken() == $currentCursor) break 2;
        $currentCursor = $payment->getPagingToken(); 

        printf('%s [%s] Amount: %s From %s %s ' . PHP_EOL,
            $currentCursor,
            $payment->getAssetTransferType(),
            $payment->getAssetAmount(),
            $payment->getFromAccountId() , $txid

        );
    }
    // Immediate exit if there aren't enough results to fill the page
    if ($seenResults < $resultsPerPage) break;
}
```

But there is a problem to distinguish different payments we need to check memo field of the transaction. 
How to do it properly?

Also another question - is there any confirmations in stellar or validation of the transaction? And how to check it?

Thank you.

**Comment by zulucrypto** [comment]
Hello,
Since the memo is stored on the Transaction you'd need to look up the Transaction based on its hash. Unfortunately, the library doesn't currently have an easy way to do this.

It would work something like this:

1. For each payment you find, get its transaction hash via `$payment->getTransactionHash()`
1. Look up the Transaction. As of now this would be a manual call to the Horizon endpoint: https://www.stellar.org/developers/horizon/reference/endpoints/transactions-single.html
1. Read the memo from there

As far as confirmations go, due to Stellar's consensus model only one "confirmation" is needed, so anything you see on the blockchain is confirmed and validated.

**Comment by gituser** [comment]
Hi!

Thank you for your reply.

>For each payment you find, get its transaction hash via $payment->getTransactionHash()

There is an error by the way, if the payment type is `createAccount` there is no method `getTransactionHash()` in the class..

Here is how we did this (maybe it will be helpful for others):

```
use ZuluCrypto\StellarSdk\Server;
$server = Server::testNet();
$account = $server->getAccount('XXXXXX');
$currentCursor = null;
while (true) {
    $resultsPerPage = 10;
    $transactions = $account->getTransactions(null, $resultsPerPage);
    $seenResults = 0;
    foreach ($transactions as $transaction) {
        // If the same cursor shows up twice, we're repeating results and should exit
        $payments = $transaction->getPayments(null, 100);
        $memo = $transaction->getMemo();
        $txhash = $transaction->getHash();
        foreach ($payments as $payment) {
          if ($payment->getPagingToken() == $currentCursor) break 2;
          printf('[%s] Amount: %s From %s Txhash %s Memo %s' . PHP_EOL,
            $payment->getAssetTransferType(),
            $payment->getAssetAmount(),
            $payment->getFromAccountId(),
            $txhash,
            $memo            
          );
          $currentCursor = $payment->getPagingToken();
        }
    }
    // Immediate exit if there aren't enough results to fill the page
    if ($seenResults < $resultsPerPage) break;
}
```

**Comment by gituser** [comment]
Also, I have a question:

What is the best way to handle multiple payments per 1 transaction to the same account (e.g. deposit)?

**Comment by gituser** [comment]
this one can be closed

**Comment by minherc** [comment]
> Привет.
> 
> Мы находимся в процессе интеграции Stellar в нашу службу обмена и хотели спросить, каков наилучший метод для отслеживания платежей на наш счет через вашу библиотеку API.
> 
> Мы используем ваш пример, чтобы получить все платежи на наш счет:
> 
> ```
> use ZuluCrypto\StellarSdk\Server;
> $server = Server::testNet();
> $account = $server->getAccount('XXXXX');
> $currentCursor = null;
> while (true) {
>     $resultsPerPage = 10;
>     $payments = $account->getPayments(null, $resultsPerPage);
>     $seenResults = 0;
>     foreach ($payments as $payment) {
>         // If the same cursor shows up twice, we're repeating results and should exit
> if (method_exists($payment,'getTransactionHash')) $txid= $payment->getTransactionHash(); else $txid = 'n/a';
>         if ($payment->getPagingToken() == $currentCursor) break 2;
>         $currentCursor = $payment->getPagingToken(); 
> 
>         printf('%s [%s] Amount: %s From %s %s ' . PHP_EOL,
>             $currentCursor,
>             $payment->getAssetTransferType(),
>             $payment->getAssetAmount(),
>             $payment->getFromAccountId() , $txid
> 
>         );
>     }
>     // Immediate exit if there aren't enough results to fill the page
>     if ($seenResults < $resultsPerPage) break;
> }
> ```
> Но есть проблема, чтобы отличить различные платежи, нам нужно проверить поле «Памятка» транзакции. 
> Как это сделать правильно?
> 
> Также еще один вопрос - есть ли какие-либо подтверждения в звездной или валидации транзакции? И как это проверить?
> 
> Спасибо.

I was also looking for an easy way to do it and found it))
[https://github.com/stellar/go/tree/master/services/bridge](https://github.com/stellar/go/tree/master/services/bridge)

**Comment by gituser** [comment]
@minherc there is a solution already posted in this issue: https://github.com/zulucrypto/stellar-api/issues/26#issuecomment-418685187

Please post your questions only in English.

**Comment by minherc** [comment]
> "We're in the process of integrating Stellar into our exchange service and wanted to ask what is the **best method to monitor payments to our account** via your API library."


This library has no such methods. The best solution is to install the Stellar Bridge server, which has a callback when a new payment is received.

**Comment by gituser** [comment]
@minherc no, you're wrong, the library has the method to check for new payments arriving on your account.

The key to success:
1. Store $currentCursor somewhere
2. Use the code I posted above with the $currentCursor and implement necessary logic to credit your user deposits or process certain transactions.
3. I never heard about Stellar Bridge and not quite sure if it's properly maintained and won't break at some point for you.
4. The Zulucrypto stellar-api library has been solid since the time we've implemented it. However we're not using the latest version because of the PHP 7.x requirement as we're still using 5.6.

**Comment by minherc** [comment]
@gituser 
This is not the best method you would like. 
My method from the developers STELLAR, has the appropriate speed and reliability.

**Comment by gituser** [comment]
@minherc ok, you're free to use what you want, would be nice if you could share your setup later and how it works for you.

**Comment by minherc** [comment]
Works great! BRIDGE through the callback loads the page that I specified in its configuration. Through POST he gives all the information on the payment. The script on this page writes payment information to the database, and sends me a notification via SLACK. The processing on the callback page can be customized.
