### ISSUE TITLE
[Question] How to check if Stellar's account is valid or exist?

### ISSUE THREAD

**Issue by gituser** [zulucrypto/stellar-api#27]
Hi!

Is there any method to check if the submitted by user (customer) account is valid ?

Is there any method to check if user submitted the valid stellar account if it exists or not (e.g. it's funded) ?

Thanks!

**Comment by gituser** [comment]
Take a look at this code: https://github.com/atticlab/stellar-php/blob/master/src/Account.php#L127
and https://github.com/atticlab/stellar-php/blob/master/src/Account.php#L104

Would be nice if you could implement both checks in your library.

Thanks!

**Comment by zulucrypto** [comment]
Thanks for those links. I've added similar methods as part of 0.7.0:

 * `Account::isValidAccount` to check if a keypair is valid
 * `Server::accountExists` to check if an account is funded on the network
