### ISSUE TITLE
[Bug] no getTransactionHash() method in createAccountOperation class

### ISSUE THREAD

**Issue by gituser** [zulucrypto/stellar-api#28]
If you use the provided example from getting-started/06-list-operations.php and add there in the printf:

```php
printf('[%s] Amount: %s From %s Txhash %s' . PHP_EOL,
            $payment->getAssetTransferType(),
            $payment->getAssetAmount(),
            $payment->getFromAccountId(),
            $payment->getTransactionHash()
        );
```
There will be an error: if the payment type is createAccountOperation (which is always 1st transaction on any Stellar account) there is no method getTransactionHash() in the `createAccountOperation` class.

The only way right now is to list transactions instead of payments and then grab payments from there.

**Comment by zulucrypto** [comment]
Thanks for the report, this was fixed in 0.7.0. I've promoted `getTransactionHash` up to the Operation level, so it should be available on all operations where Horizon includes this as a response.
