### ISSUE TITLE
getAmount returns the sequence number

### ISSUE THREAD

**Issue by AhMyth** [zulucrypto/stellar-api#38]
Thanks for this Great php lib,

When doing 
```php
PaymentOp::fromXdr($xdr)->getAmount()->getScaledValue();
```
the output is the sequence number of the transaction `311705963.0170122` instead of the amount (balance).
This is the xdr that I have used on this case:

`AAAAAIuaSLiJLh5eGb04hoWf820GwmU2L4goNDUuu2ccYAXTAAAAZAALEvMAAAAKAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAuLNRSm91r71065lPhyRAMSmVSuduSXX+I+fJ+gub8rQAAAAAAAAAAAvrwgAAAAAAAAAAARxgBdMAAABAQ5z/9lCvOWYGL74qZJNLgD+39qpaK+DHzmdP4Ni6CCXZON4pRyr94cJeQc5reWr1qUqzqb00sfeRdgTTRDsRAw==`

**Comment by Ralzanonymus** [comment]
311705963.0170122
