### ISSUE TITLE
Uncaught Error: Call to undefined method ZuluCrypto\StellarSdk\Model\AssetAmount::getBalanceString()

### ISSUE THREAD

**Issue by natrod** [zulucrypto/stellar-api#8]
we get the following error in line 20 of the 03-account-details.php file

PHP Fatal error:  Uncaught Error: Call to undefined method ZuluCrypto\StellarSdk\Model\AssetAmount::getBalanceString() in /var/www/html/stellar-api/getting-started/03-account-details.php:20
Stack trace:
#0 {main}
  thrown in /var/www/html/test/stellar-api/getting-started/03-account-details.php on line 20

not sure on intended code is 
`$balance->__toString()`
or 
`$balance->getBalance()`

**Comment by zulucrypto** [comment]
Thanks for reporting this, I've fixed it and released 0.6.0

**Comment by natrod** [comment]
Thank you :) I appreciate your hard work, I'm using your library on a project of mine and will try to report and fix any bugs i encounter.
